name: caml
description: A simple new data-storing format for Dart nerds and simplicty enthusiasts.
version: 1.0.0
homepage: https://github.com/iamtheblackunicorn/caml
environment:
  sdk: '>=2.12.0 <3.0.0'
dev_dependencies:
  pedantic: ^1.9.0
  clibu: ^1.5.0
  termstyle: ^1.7.0
